# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecb130336582d78f5e25c6b3077eeddbc4e74345da38bdd02b1ff6c7c63119f6863a0491b366e6345b3529eb1228510f290b3292f9fc05e1e25c9b89ad6e944e

test:
  secret_key_base: 4d08f5e3b215950f1a9ca1ab2d42c4ce0553d953f81e40b305cee496662e06742d9ef33b61599d3d02819ea6c7cd7ba4c06a91658e138b23efb4fcf158e69b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
